### ISSUE TITLE
Can't find classes in JAR because of addClassLoader in ConfigurationBuilder

### ISSUE THREAD

**Issue by jomp16** [aschoerk/reflections8#8]
I create a instance of Reflections with this piece of code:

`val reflections = Reflections(ConfigurationBuilder().addUrls(URL("file:" + jarFile.path)).addClassLoader(urlClassLoader))`

But it can't find any classes (actually it can find, but it can't resolve the type) because of missing classloader.

See this line of method addClassLoader:

https://github.com/aschoerk/reflections8/blob/97c5820b44a8607da418cdbac7f6f0a71525589a/src/main/java/org/reflections8/util/ConfigurationBuilder.java#L342

If classloader isn't present (Optional.empty()), it returns, without even adding the classloader!

I compared with original Reflections project:

https://github.com/ronmamo/reflections/blob/43ee4af53a654006d230bb667ba2cf166ef1e2a8/src/main/java/org/reflections/util/ConfigurationBuilder.java#L301

Obviously it always adds the new classloader.

My workaround is calling the setter directly, and that makes Reflections resolve the classes:

```
val configurationBuilder = ConfigurationBuilder().setUrls(URL("file:" + jarFile.absolutePath))
configurationBuilder.classLoaders = Optional.of(arrayOf(urlClassLoader))
```

**Comment by jomp16** [comment]
The suggested fix above makes it works again, finding the type of the classes using the classloader.

**Comment by aschoerk** [comment]
Solved by issuer
